### ISSUE TITLE
FR: VPN provider lookup

### ISSUE THREAD

**Issue by mgaulton** [mitchmoser/sputnik#14]
In managing out Office 365 and its overly sensitive impossible travel rules :) we have a need to be able to quickly determine with a reasonable likely hood if something is a VPN provide or not based on the IP address.

A look up against https://github.com/ejrv/VPNs or something similar would be awesome.
I really appreciate your efforts. This saves having to load maltego constantly :)

**Comment by mitchmoser** [comment]
Thanks for the feature request. I did some research into this and tried to find some integrations that would help you identify VPN IP addresses in web portal. 

Rather than adding a lookup against a txt file in the link you've provided, are there any web sites that you use to perform this search that we can integrate into Sputnik? I'd like to keep the user interaction and the extension's behavior consistent across all integrations as much as possible.

**Comment by mgaulton** [comment]
Sadly, I haven't found any other good resources in the area of this.

**Comment by mgaulton** [comment]
Oh, i found this! 
https://www.ipqualityscore.com

**Comment by mitchmoser** [comment]
27a6acc

Added IP Quality Score to IP Lookup. Thank you for your input.
