### ISSUE TITLE
Firefox for android doesnt support context menus but

### ISSUE THREAD

**Issue by foi** [mitchmoser/sputnik#7]
At firefox addons store it available for install. 

Webextensions api restrictions: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus

**Comment by mitchmoser** [comment]
As you've stated, Firefox Android is not supported by Mozilla's contextMenu API which is fundamental to this plugin's functionality.

Since there is no way to exclude distribution to Firefox Android from the Add-on Store, a note has been added to the Firefox Add-on Store entry to state that the Mozilla API does not support this extension for Firefox Android.

**Comment by foi** [comment]
@mitchmoser when you uploading new version you can setup compatability
![11111111111111111111111111111](https://user-images.githubusercontent.com/26715/50875481-2c274180-13fb-11e9-892f-5993ad3047e2.jpg)
