### ISSUE TITLE
Clipboard issue/no new Tab/Window

### ISSUE THREAD

**Issue by Zeik0s** [mitchmoser/sputnik#9]
Hi,

 

I have this strange problem, that no new tab/window/whatever opens and shows the corresponding Result.

This doesn't happen on my second PC, where I use almost the same Setup.

 

I am using Firefox ESR 60.4 on Windows 10 64bit

 

This is the Debug Log from the Addon:

```

Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered.  components.manifest:166

navigator.clipboard is undefined background.js:533

navigator.clipboard is undefined  background.js:533

            <anonym> moz-extension://a7e90cc9-3dbe-4296-a62d-5b0ce53f7c50/background.js:533:5

            apply self-hosted:4294:5

            applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:304:16

            applySafe resource://gre/modules/ExtensionCommon.jsm:291:14

            sync resource://gre/modules/ExtensionCommon.jsm:1797:18

            listener/< chrome://browser/content/ext-c-menus.js:168:41

            withHandlingUserInput resource://gre/modules/ExtensionUtils.jsm:130:12

            listener chrome://browser/content/ext-c-menus.js:167:13

            apply self-hosted:4294:5

            applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:304:16

            fire resource://gre/modules/ExtensionChild.jsm:881:28

            receiveMessage resource://gre/modules/ExtensionChild.jsm:884:38

            _callHandlers/< resource://gre/modules/MessageChannel.jsm:864:17

            _callHandlers resource://gre/modules/MessageChannel.jsm:863:14

            _handleMessage/deferred.promise< resource://gre/modules/MessageChannel.jsm:938:7

            _handleMessage resource://gre/modules/MessageChannel.jsm:935:24

            _handleMessage self-hosted:978:17

            receiveMessage/< resource://gre/modules/MessageChannel.jsm:208:9

            forEach self-hosted:261:13

            receiveMessage resource://gre/modules/MessageChannel.jsm:201:5

```

 

Do you know more about it?

**Comment by mitchmoser** [comment]
Thank you for submitting this issue. I've not been able to reproduce this bug on my end and it looks like you're also unable to reproduce it on your second setup as well.

Try updating or reinstalling Sputnik and see if this issue persists. If it does, please outline the steps to reproduce this bug and open another issue. I'll gladly look into it!

**Comment by Zeik0s** [comment]
Hi @mitchmoser, sorry for bothering you again.

I had some time and was able to reproduce the Issue on a third machine with no firefox on it before.

1. Install Firefox ESR (it's not relevant if it's 60.4.1 or the newest Version 60.5)
2. Install Sputnik
3. Open an IOC

Result: Nothing happens

So i think it's a missing feature from the Extended Support Release of Firefox, maybe it get's the feature later on for improving Stability.

**Comment by mitchmoser** [comment]
Awesome, thank you for this! I was able to do a little bit of digging, fired up a Windows 10 VM with Fireox ESR, and I was able to recreate this issue.

What I found is ESR does not currently implement the Mozilla clipboard API which is used by Sputnik. Therefore, the "copying a highlighted artifact to the clipboard" feature will be missing in Firefox ESR until the Mozilla clipboard API is implemented.

This appears to be due to Firefox ESR being generally more stable, so it is modified at a slower rate and doesn't incorporate all current features until they have been fully determined not to break anything or cause other compatibility problems.

I pushed a Firefox update for Sputnik Version 1.20 to improve compatibility with Firefox ESR. This update gives ESR users all of the functionality aside from the highlighted artifacts being copied to the clipboard.

Thanks again for bringing this issue to my attention.
